### ISSUE TITLE
関数型インタフェースは実装すべきメソッドが単一の関数

### ISSUE THREAD

**Issue by bitterfox** [skrb/LambdaDojo#1]
`L61:        <p>文法的には、Lambda 式は関数型インタフェースを実装した匿名クラスの簡易的な記述法とみなせます。関数型インタフェースは実装すべきメソッドが単一の関数で @FunctionalInterface でインタフェースが修飾されています。</p>`
実装すべきメソッドが単一のインタフェース？

**Comment by skrb** [comment]
修正しました。
